---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: shell
os: linux
git:
  depth: 1
dist: bionic

jobs:
  include:
    - name: Lint validation
      language: python
      install:
        - pip install tox
      script:
        - tox -e bashate
        - bash -c 'shopt -s globstar; shellcheck -x **/*.sh'
    - name: All-in-One Ubuntu 18.04 LTS validation
      script:
        - ./node.sh
        - OS_FOLDER=$(git rev-parse --show-toplevel) OS_KOLLA_ENABLE_CINDER=no ./install.sh
