---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

# Network Definitions:

# Management Network - This interface is used by OpenStack services and databases to communicate to each other.
# Tunnel Network - This interface is used by Neutron for vm-to-vm traffic over tunnel-neted networks (like VxLan).
# Storage Network - This interface is used virtual machines to communicate to Ceph.
# External Network - This is the raw interface given to neutron as its external network port.

- name: "registry"
  memory: 16384
  cpus: 16
  volumes:
    - name: sda
      size: 100
      mount: /var/lib/docker/
  networks:
    - name: tunnel-net
      ip: "10.10.13.2"
  roles:
    - registry
- name: "control01"
  memory: 16384
  cpus: 8
  networks:
    - name: tunnel-net
      ip: "10.10.13.4"
  roles:
    - controller
- name: "control02"
  memory: 16384
  cpus: 8
  networks:
    - name: tunnel-net
      ip: "10.10.13.5"
  roles:
    - controller
- name: "control03"
  memory: 16384
  cpus: 8
  networks:
    - name: tunnel-net
      ip: "10.10.13.6"
  roles:
    - controller
- name: "compute01"
  memory: 65536
  cpus: 16
  networks:
    - name: tunnel-net
      ip: "10.10.13.33"
    - name: storage-net
      ip: "10.10.14.33"
  roles:
    - compute
- name: "network01"
  memory: 8192
  cpus: 4
  networks:
    - name: tunnel-net
      ip: "10.10.13.65"
  roles:
    - network
- name: "network02"
  memory: 8192
  cpus: 4
  networks:
    - name: tunnel-net
      ip: "10.10.13.66"
  roles:
    - network
- name: "network03"
  memory: 8192
  cpus: 4
  networks:
    - name: tunnel-net
      ip: "10.10.13.67"
  roles:
    - network
- name: "storage01"
  memory: 8192
  cpus: 4
  networks:
    - name: tunnel-net
      ip: "10.10.13.97"
    - name: storage-net
      ip: "10.10.14.97"
  roles:
    - storage-net
- name: "monitoring01"
  memory: 8192
  cpus: 4
  networks:
    - name: tunnel-net
      ip: "10.10.13.129"
  roles:
    - monitoring
