---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: "control01"
  ip: "10.10.10.3"
  memory: 8192
  cpus: 2
- name: "control02"
  ip: "10.10.10.4"
  memory: 8192
  cpus: 2
- name: "control03"
  ip: "10.10.10.5"
  memory: 8192
  cpus: 2
- name: "compute01"
  ip: "10.10.10.6"
  memory: 8192
  cpus: 2
- name: "network01"
  ip: "10.10.10.7"
  memory: 8192
  cpus: 2
- name: "network02"
  ip: "10.10.10.8"
  memory: 8192
  cpus: 2
- name: "storage01"
  ip: "10.10.10.9"
  memory: 8192
  cpus: 2
- name: "monitoring01"
  ip: "10.10.10.9"
  memory: 8192
  cpus: 2
